// PermissionCatalog.java completo com todos os grupos Fase 2 e Fase 3
package br.com.seuprojeto.consents.rules.v2;

import br.com.seuprojeto.consents.enums.PermissionEnum;

import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class PermissionCatalog {

    // ------------------- Fase 2 -------------------
    public static final Set<String> FASE2_OBRIGATORIAS = Set.of("RESOURCES_READ");
    public static final Set<String> FASE2_PERMISSOES = PermissionEnum.getFase2Permissions();

    public static final Map<String, Set<String>> FASE2_REQUIRED_GROUPS = Map.of(
            "CREDIT", Set.of("CREDIT_OPERATIONS_READ"),
            "INVESTMENTS", Set.of("INVESTMENTS_READ"),
            "EXCHANGES", Set.of("EXCHANGES_READ")
    );

    // ------------------- Fase 3 -------------------
    public static final Map<String, Set<String>> FASE3_REQUIRED_BY_GROUP = Map.ofEntries(
            Map.entry("CLAIM_NOTIFICATION_REQUEST_DAMAGE", Set.of("CLAIM_NOTIFICATION_REQUEST_DAMAGE_CREATE")),
            Map.entry("CLAIM_NOTIFICATION_REQUEST_PERSON", Set.of("CLAIM_NOTIFICATION_REQUEST_PERSON_CREATE")),
            Map.entry("ENDORSEMENT_REQUEST", Set.of("ENDORSEMENT_REQUEST_CREATE")),
            Map.entry("QUOTE_AUTO", Set.of("QUOTE_AUTO_READ", "QUOTE_AUTO_CREATE", "QUOTE_AUTO_UPDATE")),
            Map.entry("QUOTE_AUTO_LEAD", Set.of("QUOTE_AUTO_LEAD_CREATE", "QUOTE_AUTO_LEAD_UPDATE")),
            Map.entry("QUOTE_PATRIMONIAL_LEAD", Set.of("QUOTE_PATRIMONIAL_LEAD_CREATE", "QUOTE_PATRIMONIAL_LEAD_UPDATE")),
            Map.entry("QUOTE_PATRIMONIAL_HOME", Set.of("QUOTE_PATRIMONIAL_HOME_READ", "QUOTE_PATRIMONIAL_HOME_CREATE", "QUOTE_PATRIMONIAL_HOME_UPDATE")),
            Map.entry("QUOTE_PATRIMONIAL_CONDOMINIUM", Set.of("QUOTE_PATRIMONIAL_CONDOMINIUM_READ", "QUOTE_PATRIMONIAL_CONDOMINIUM_CREATE", "QUOTE_PATRIMONIAL_CONDOMINIUM_UPDATE")),
            Map.entry("QUOTE_PATRIMONIAL_BUSINESS", Set.of("QUOTE_PATRIMONIAL_BUSINESS_READ", "QUOTE_PATRIMONIAL_BUSINESS_CREATE", "QUOTE_PATRIMONIAL_BUSINESS_UPDATE")),
            Map.entry("QUOTE_PATRIMONIAL_DIVERSE_RISKS", Set.of("QUOTE_PATRIMONIAL_DIVERSE_RISKS_READ", "QUOTE_PATRIMONIAL_DIVERSE_RISKS_CREATE", "QUOTE_PATRIMONIAL_DIVERSE_RISKS_UPDATE")),
            Map.entry("QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD", Set.of("QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_CREATE", "QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_UPDATE")),
            Map.entry("QUOTE_FINANCIAL_RISK_LEAD", Set.of("QUOTE_FINANCIAL_RISK_LEAD_CREATE", "QUOTE_FINANCIAL_RISK_LEAD_UPDATE")),
            Map.entry("QUOTE_HOUSING_LEAD", Set.of("QUOTE_HOUSING_LEAD_CREATE", "QUOTE_HOUSING_LEAD_UPDATE")),
            Map.entry("QUOTE_RESPONSIBILITY_LEAD", Set.of("QUOTE_RESPONSIBILITY_LEAD_CREATE", "QUOTE_RESPONSIBILITY_LEAD_UPDATE")),
            Map.entry("QUOTE_RURAL_LEAD", Set.of("QUOTE_RURAL_LEAD_CREATE", "QUOTE_RURAL_LEAD_UPDATE")),
            Map.entry("QUOTE_TRANSPORT_LEAD", Set.of("QUOTE_TRANSPORT_LEAD_CREATE", "QUOTE_TRANSPORT_LEAD_UPDATE")),
            Map.entry("QUOTE_PERSON_LEAD", Set.of("QUOTE_PERSON_LEAD_CREATE", "QUOTE_PERSON_LEAD_UPDATE")),
            Map.entry("QUOTE_PERSON_LIFE", Set.of("QUOTE_PERSON_LIFE_READ", "QUOTE_PERSON_LIFE_CREATE", "QUOTE_PERSON_LIFE_UPDATE")),
            Map.entry("QUOTE_PERSON_TRAVEL", Set.of("QUOTE_PERSON_TRAVEL_READ", "QUOTE_PERSON_TRAVEL_CREATE", "QUOTE_PERSON_TRAVEL_UPDATE")),
            Map.entry("QUOTE_CAPITALIZATION_TITLE", Set.of("QUOTE_CAPITALIZATION_TITLE_READ", "QUOTE_CAPITALIZATION_TITLE_CREATE", "QUOTE_CAPITALIZATION_TITLE_UPDATE")),
            Map.entry("QUOTE_CAPITALIZATION_TITLE_LEAD", Set.of("QUOTE_CAPITALIZATION_TITLE_LEAD_CREATE", "QUOTE_CAPITALIZATION_TITLE_LEAD_UPDATE")),
            Map.entry("QUOTE_CAPITALIZATION_TITLE_RAFFLE", Set.of("QUOTE_CAPITALIZATION_TITLE_RAFFLE_CREATE")),
            Map.entry("CONTRACT_LIFE_PENSION", Set.of("CONTRACT_LIFE_PENSION_CREATE", "CONTRACT_LIFE_PENSION_UPDATE", "CONTRACT_LIFE_PENSION_READ")),
            Map.entry("CONTRACT_LIFE_PENSION_LEAD", Set.of("CONTRACT_LIFE_PENSION_LEAD_CREATE", "CONTRACT_LIFE_PENSION_LEAD_UPDATE")),
            Map.entry("CONTRACT_LIFE_PENSION_LEAD_PORTABILITY", Set.of("CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_CREATE", "CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_UPDATE")),
            Map.entry("CONTRACT_PENSION_PLAN_LEAD", Set.of("CONTRACT_PENSION_PLAN_LEAD_CREATE", "CONTRACT_PENSION_PLAN_LEAD_UPDATE")),
            Map.entry("CONTRACT_PENSION_PLAN_LEAD_PORTABILITY", Set.of("CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_CREATE", "CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_UPDATE")),
            Map.entry("PENSION_WITHDRAWAL", Set.of("PENSION_WITHDRAWAL_CREATE")),
            Map.entry("PENSION_WITHDRAWAL_LEAD", Set.of("PENSION_WITHDRAWAL_LEAD_CREATE")),
            Map.entry("CAPITALIZATION_TITLE_WITHDRAWAL", Set.of("CAPITALIZATION_TITLE_WITHDRAWAL_CREATE")),
            Map.entry("PERSON_WITHDRAWAL", Set.of("PERSON_WITHDRAWAL_CREATE"))
    );
}
