// PermissionEnum.java completo com metadados de fase
package br.com.seuprojeto.consents.enums;

import lombok.Getter;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

@Getter
public enum PermissionEnum {

    // --- Fase 2 ---
    CAPITALIZATION_TITLE_EVENTS_READ("FASE2"),
    CAPITALIZATION_TITLE_PLANINFO_READ("FASE2"),
    CAPITALIZATION_TITLE_READ("FASE2"),
    CAPITALIZATION_TITLE_SETTLEMENTS_READ("FASE2"),
    CUSTOMERS_BUSINESS_ADDITIONALINFO_READ("FASE2"),
    CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ("FASE2"),
    CUSTOMERS_BUSINESS_QUALIFICATION_READ("FASE2"),
    CUSTOMERS_PERSONAL_ADDITIONALINFO_READ("FASE2"),
    CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ("FASE2"),
    CUSTOMERS_PERSONAL_QUALIFICATION_READ("FASE2"),
    DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_READ("FASE2"),
    DAMAGES_AND_PEOPLE_AUTO_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_AUTO_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_AUTO_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_AUTO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_READ("FASE2"),
    DAMAGES_AND_PEOPLE_HOUSING_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_HOUSING_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_HOUSING_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_HOUSING_READ("FASE2"),
    DAMAGES_AND_PEOPLE_PATRIMONIAL_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_PATRIMONIAL_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_PATRIMONIAL_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_PATRIMONIAL_READ("FASE2"),
    DAMAGES_AND_PEOPLE_PERSON_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_PERSON_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_PERSON_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_PERSON_READ("FASE2"),
    DAMAGES_AND_PEOPLE_RESPONSIBILITY_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_RESPONSIBILITY_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_RESPONSIBILITY_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_RESPONSIBILITY_READ("FASE2"),
    DAMAGES_AND_PEOPLE_RURAL_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_RURAL_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_RURAL_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_RURAL_READ("FASE2"),
    DAMAGES_AND_PEOPLE_TRANSPORT_CLAIM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_TRANSPORT_POLICYINFO_READ("FASE2"),
    DAMAGES_AND_PEOPLE_TRANSPORT_PREMIUM_READ("FASE2"),
    DAMAGES_AND_PEOPLE_TRANSPORT_READ("FASE2"),
    FINANCIAL_ASSISTANCE_CONTRACTINFO_READ("FASE2"),
    FINANCIAL_ASSISTANCE_MOVEMENTS_READ("FASE2"),
    FINANCIAL_ASSISTANCE_READ("FASE2"),
    LIFE_PENSION_CLAIM("FASE2"),
    LIFE_PENSION_CONTRACTINFO_READ("FASE2"),
    LIFE_PENSION_MOVEMENTS_READ("FASE2"),
    LIFE_PENSION_PORTABILITIES_READ("FASE2"),
    LIFE_PENSION_READ("FASE2"),
    LIFE_PENSION_WITHDRAWALS_READ("FASE2"),
    PENSION_PLAN_CLAIM("FASE2"),
    PENSION_PLAN_CONTRACTINFO_READ("FASE2"),
    PENSION_PLAN_MOVEMENTS_READ("FASE2"),
    PENSION_PLAN_PORTABILITIES_READ("FASE2"),
    PENSION_PLAN_READ("FASE2"),
    PENSION_PLAN_WITHDRAWALS_READ("FASE2"),
    RESOURCES_READ("FASE2"),

    // --- Fase 3 ---
    CAPITALIZATION_TITLE_WITHDRAWAL_CREATE("FASE3"),
    CLAIM_NOTIFICATION_REQUEST_DAMAGE_CREATE("FASE3"),
    CLAIM_NOTIFICATION_REQUEST_PERSON_CREATE("FASE3"),
    CONTRACT_LIFE_PENSION_CREATE("FASE3"),
    CONTRACT_LIFE_PENSION_LEAD_CREATE("FASE3"),
    CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_CREATE("FASE3"),
    CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_UPDATE("FASE3"),
    CONTRACT_LIFE_PENSION_LEAD_UPDATE("FASE3"),
    CONTRACT_LIFE_PENSION_READ("FASE3"),
    CONTRACT_LIFE_PENSION_UPDATE("FASE3"),
    CONTRACT_PENSION_PLAN_LEAD_CREATE("FASE3"),
    CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_CREATE("FASE3"),
    CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_UPDATE("FASE3"),
    CONTRACT_PENSION_PLAN_LEAD_UPDATE("FASE3"),
    ENDORSEMENT_REQUEST_CREATE("FASE3"),
    PENSION_WITHDRAWAL_CREATE("FASE3"),
    PENSION_WITHDRAWAL_LEAD_CREATE("FASE3"),
    PERSON_WITHDRAWAL_CREATE("FASE3"),
    QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_CREATE("FASE3"),
    QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_UPDATE("FASE3"),
    QUOTE_AUTO_CREATE("FASE3"),
    QUOTE_AUTO_LEAD_CREATE("FASE3"),
    QUOTE_AUTO_LEAD_UPDATE("FASE3"),
    QUOTE_AUTO_READ("FASE3"),
    QUOTE_AUTO_UPDATE("FASE3"),
    QUOTE_CAPITALIZATION_TITLE_CREATE("FASE3"),
    QUOTE_CAPITALIZATION_TITLE_LEAD_CREATE("FASE3"),
    QUOTE_CAPITALIZATION_TITLE_LEAD_UPDATE("FASE3"),
    QUOTE_CAPITALIZATION_TITLE_RAFFLE_CREATE("FASE3"),
    QUOTE_CAPITALIZATION_TITLE_READ("FASE3"),
    QUOTE_CAPITALIZATION_TITLE_UPDATE("FASE3"),
    QUOTE_FINANCIAL_RISK_LEAD_CREATE("FASE3"),
    QUOTE_FINANCIAL_RISK_LEAD_UPDATE("FASE3"),
    QUOTE_HOUSING_LEAD_CREATE("FASE3"),
    QUOTE_HOUSING_LEAD_UPDATE("FASE3"),
    QUOTE_PATRIMONIAL_BUSINESS_CREATE("FASE3"),
    QUOTE_PATRIMONIAL_BUSINESS_READ("FASE3"),
    QUOTE_PATRIMONIAL_BUSINESS_UPDATE("FASE3"),
    QUOTE_PATRIMONIAL_CONDOMINIUM_CREATE("FASE3"),
    QUOTE_PATRIMONIAL_CONDOMINIUM_READ("FASE3"),
    QUOTE_PATRIMONIAL_CONDOMINIUM_UPDATE("FASE3"),
    QUOTE_PATRIMONIAL_DIVERSE_RISKS_CREATE("FASE3"),
    QUOTE_PATRIMONIAL_DIVERSE_RISKS_READ("FASE3"),
    QUOTE_PATRIMONIAL_DIVERSE_RISKS_UPDATE("FASE3"),
    QUOTE_PATRIMONIAL_HOME_CREATE("FASE3"),
    QUOTE_PATRIMONIAL_HOME_READ("FASE3"),
    QUOTE_PATRIMONIAL_HOME_UPDATE("FASE3"),
    QUOTE_PATRIMONIAL_LEAD_CREATE("FASE3"),
    QUOTE_PATRIMONIAL_LEAD_UPDATE("FASE3"),
    QUOTE_PERSON_LEAD_CREATE("FASE3"),
    QUOTE_PERSON_LEAD_UPDATE("FASE3"),
    QUOTE_PERSON_LIFE_CREATE("FASE3"),
    QUOTE_PERSON_LIFE_READ("FASE3"),
    QUOTE_PERSON_LIFE_UPDATE("FASE3"),
    QUOTE_PERSON_TRAVEL_CREATE("FASE3"),
    QUOTE_PERSON_TRAVEL_READ("FASE3"),
    QUOTE_PERSON_TRAVEL_UPDATE("FASE3"),
    QUOTE_RESPONSIBILITY_LEAD_CREATE("FASE3"),
    QUOTE_RESPONSIBILITY_LEAD_UPDATE("FASE3"),
    QUOTE_RURAL_LEAD_CREATE("FASE3"),
    QUOTE_RURAL_LEAD_UPDATE("FASE3"),
    QUOTE_TRANSPORT_LEAD_CREATE("FASE3"),
    QUOTE_TRANSPORT_LEAD_UPDATE("FASE3");

    private final String fase;

    PermissionEnum(String fase) {
        this.fase = fase;
    }

    public static Set<String> getFase2Permissions() {
        return Arrays.stream(values())
                .filter(p -> "FASE2".equals(p.getFase()))
                .map(Enum::name)
                .collect(Collectors.toSet());
    }

    public static Set<String> getFase3Permissions() {
        return Arrays.stream(values())
                .filter(p -> "FASE3".equals(p.getFase()))
                .map(Enum::name)
                .collect(Collectors.toSet());
    }

}
